export const users = [
  {
    id: 1,
    name: "John",
    surname: "Smith",
    country: "USA",
    dateOfBirth: "2003-03-02",
    position: "Junior",
    married: "No",
  },
  {
    id: 2,
    name: "Tom",
    surname: "Le",
    country: "UK",
    dateOfBirth: "2002-05-01",
    position: "Middle",
    married: "Yes",
  },
  {
    id: 3,
    name: "Bruce",
    surname: "Musket",
    country: "China",
    dateOfBirth: "2000-07-03",
    position: "Sineor",
    married: "Yes",
  },
  {
    id: 4,
    name: "Sam",
    surname: "Jakob",
    country: "Turkey",
    dateOfBirth: "2003-03-01",
    position: "Middle",
    married: "No",
  },
];
